//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャプチャ(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Capture {
            get {
                return ResourceManager.GetString("ContextMenu_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択コントロールをキャプチャ(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ControlCapture {
            get {
                return ResourceManager.GetString("ContextMenu_ControlCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップ全体をキャプチャ(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DesktopCapture {
            get {
                return ResourceManager.GetString("ContextMenu_DesktopCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Settings {
            get {
                return ResourceManager.GetString("ContextMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウェブページ全体をキャプチャ(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_WebPageCapture {
            get {
                return ResourceManager.GetString("ContextMenu_WebPageCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左クリックで領域を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Description {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Name {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Position {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Size {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Capture {
            get {
                return ResourceManager.GetString("Settings_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャの遅延時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CaptureDelayTime {
            get {
                return ResourceManager.GetString("Settings_CaptureDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャオプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CaptureOption {
            get {
                return ResourceManager.GetString("Settings_CaptureOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DelayTime {
            get {
                return ResourceManager.GetString("Settings_DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Output {
            get {
                return ResourceManager.GetString("Settings_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputMethod {
            get {
                return ResourceManager.GetString("Settings_OutputMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャー時の効果音を再生する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PlaySeWhenCapture {
            get {
                return ResourceManager.GetString("Settings_PlaySeWhenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップに登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_RegisterInStartup {
            get {
                return ResourceManager.GetString("Settings_RegisterInStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクロールの遅延時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ScrollDelayTime {
            get {
                return ResourceManager.GetString("Settings_ScrollDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカットキー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートプログラム設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_StartProgram {
            get {
                return ResourceManager.GetString("Settings_StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウェブページ全体キャプチャ開始時にページ先頭に移動する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WebPageCaptureStartWhenPageFirstMove {
            get {
                return ResourceManager.GetString("Settings_WebPageCaptureStartWhenPageFirstMove", resourceCulture);
            }
        }
    }
}
