//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャプチャ(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Capture {
            get {
                return ResourceManager.GetString("ContextMenu_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択コントロールをキャプチャ(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ControlCapture {
            get {
                return ResourceManager.GetString("ContextMenu_ControlCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップ全体をキャプチャ(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DesktopCapture {
            get {
                return ResourceManager.GetString("ContextMenu_DesktopCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Settings {
            get {
                return ResourceManager.GetString("ContextMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウェブページ全体をキャプチャ(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_WebPageCapture {
            get {
                return ResourceManager.GetString("ContextMenu_WebPageCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左クリックで領域を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Description {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Name {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Position {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlSelectionInfo_Size {
            get {
                return ResourceManager.GetString("ControlSelectionInfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmaps(*.bmp)|*.bmp|JPEG Image File(*.jpg)|*.jpg|Portable Network Graphics(*.png)|*.png|CompuServe GIF Image(*.gif)|*.gif に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Services_SaveImageFileDialog_Filter {
            get {
                return ResourceManager.GetString("Services_SaveImageFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Services_SaveImageFileDialog_Title {
            get {
                return ResourceManager.GetString("Services_SaveImageFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクティブコントロールをキャプチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ActiveControlCapture {
            get {
                return ResourceManager.GetString("Settings_ActiveControlCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を自動保存する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AutoSaveImage {
            get {
                return ResourceManager.GetString("Settings_AutoSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Capture {
            get {
                return ResourceManager.GetString("Settings_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャの遅延時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CaptureDelayTime {
            get {
                return ResourceManager.GetString("Settings_CaptureDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャオプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CaptureOption {
            get {
                return ResourceManager.GetString("Settings_CaptureOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Clipboard {
            get {
                return ResourceManager.GetString("Settings_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップにショートカットを作成する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CreateShortcutToDesktop {
            get {
                return ResourceManager.GetString("Settings_CreateShortcutToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DelayTime {
            get {
                return ResourceManager.GetString("Settings_DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップ全体をキャプチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopCapture {
            get {
                return ResourceManager.GetString("Settings_DesktopCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ImageFile {
            get {
                return ResourceManager.GetString("Settings_ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   凡例:) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Legend {
            get {
                return ResourceManager.GetString("Settings_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %y: 年, %m: 月, %d: 日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LegendDate {
            get {
                return ResourceManager.GetString("Settings_LegendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %c: 連番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LegendSequence {
            get {
                return ResourceManager.GetString("Settings_LegendSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %h: 時, %n: 分, %s: 秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LegendTime {
            get {
                return ResourceManager.GetString("Settings_LegendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フォルダが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotFoundOutputFolderMessage {
            get {
                return ResourceManager.GetString("Settings_NotFoundOutputFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Ok {
            get {
                return ResourceManager.GetString("Settings_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Output {
            get {
                return ResourceManager.GetString("Settings_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力ファイル名パターン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFileNamePattern {
            get {
                return ResourceManager.GetString("Settings_OutputFileNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFolder {
            get {
                return ResourceManager.GetString("Settings_OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フォルダを指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_OutputFolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFormat {
            get {
                return ResourceManager.GetString("Settings_OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMP 画像ファイル (*.bmp) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFormatBmp {
            get {
                return ResourceManager.GetString("Settings_OutputFormatBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GIF 画像ファイル (*.gif) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFormatGif {
            get {
                return ResourceManager.GetString("Settings_OutputFormatGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JPEG 画像ファイル (*.jpg) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFormatJpg {
            get {
                return ResourceManager.GetString("Settings_OutputFormatJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PNG 画像ファイル (*.png) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputFormatPng {
            get {
                return ResourceManager.GetString("Settings_OutputFormatPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OutputMethod {
            get {
                return ResourceManager.GetString("Settings_OutputMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャー時に効果音を再生する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PlaySeWhenCapture {
            get {
                return ResourceManager.GetString("Settings_PlaySeWhenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Program {
            get {
                return ResourceManager.GetString("Settings_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタートアップに登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_RegisterInStartup {
            get {
                return ResourceManager.GetString("Settings_RegisterInStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクロールの遅延時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ScrollDelayTime {
            get {
                return ResourceManager.GetString("Settings_ScrollDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンキャプチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SecreenCapture {
            get {
                return ResourceManager.GetString("Settings_SecreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Selection {
            get {
                return ResourceManager.GetString("Settings_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択コントロールをキャプチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SelectionControlCapture {
            get {
                return ResourceManager.GetString("Settings_SelectionControlCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカットキー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカットキーの組み合わせが重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKeyDuplicationMessage {
            get {
                return ResourceManager.GetString("Settings_ShortcutKeyDuplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のショートカットキーは使用できません。
        ///
        ///{0}
        ///ショートカットキーを変更しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKeyUnusable {
            get {
                return ResourceManager.GetString("Settings_ShortcutKeyUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウェブページ全体をキャプチャ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WebPageCapture {
            get {
                return ResourceManager.GetString("Settings_WebPageCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウェブページ全体キャプチャ開始時にページ先頭に移動する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WebPageCaptureStartWhenPageFirstMove {
            get {
                return ResourceManager.GetString("Settings_WebPageCaptureStartWhenPageFirstMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_Numeric {
            get {
                return ResourceManager.GetString("Validation_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}以上、{2}以下の数値を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
