//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCap.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   キャプチャ(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Capture {
            get {
                return ResourceManager.GetString("ContextMenu_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択コントロールをキャプチャ(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ControlCapture {
            get {
                return ResourceManager.GetString("ContextMenu_ControlCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Help {
            get {
                return ResourceManager.GetString("ContextMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Option {
            get {
                return ResourceManager.GetString("ContextMenu_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ全体をキャプチャ(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_PageCapture {
            get {
                return ResourceManager.GetString("ContextMenu_PageCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面全体をキャプチャ(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_ScreenCapture {
            get {
                return ResourceManager.GetString("ContextMenu_ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左クリックで領域を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectInfo_Description {
            get {
                return ResourceManager.GetString("SelectInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectInfo_Name {
            get {
                return ResourceManager.GetString("SelectInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   座標 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectInfo_Position {
            get {
                return ResourceManager.GetString("SelectInfo_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectInfo_Size {
            get {
                return ResourceManager.GetString("SelectInfo_Size", resourceCulture);
            }
        }
    }
}
